const BOILERPLATE_PATTERNS = [
  /all rights reserved/gi,
  /this (document|communication) (is|may be) confidential/gi,
  /please consider the environment before printing/gi,
  /terms and conditions apply/gi,
  /this message and any attachments?/gi,
  /generated by .* system/gi
];

const TABLE_HINT = /\|\s|\s\|\s|\t|\b(qty|quantity|unit price|amount|line total|sku|item)\b/i;
const REFERENCE_HINT = /(po|invoice|quote|ref|reference|id|order)\s*[:#-]?\s*[A-Z0-9][A-Z0-9-]{2,}/i;

function normalizeWhitespace(line) {
  return line.replace(/\u00A0/g, ' ').replace(/[ \t]+/g, ' ').trim();
}

function isLikelyStructured(line) {
  return TABLE_HINT.test(line) || REFERENCE_HINT.test(line);
}

function stripBoilerplate(line) {
  let next = line;
  for (const pattern of BOILERPLATE_PATTERNS) {
    next = next.replace(pattern, '').trim();
  }
  return next;
}

export function preprocessSourceText(text) {
  const normalizedText = String(text ?? '').replace(/\r\n?/g, '\n');
  const rawLines = normalizedText.split('\n').map((line) => line.trimEnd());
  const headerFooterCounts = new Map();

  for (const rawLine of rawLines) {
    const normalizedLine = normalizeWhitespace(rawLine).toLowerCase();
    if (normalizedLine.length < 3) continue;
    headerFooterCounts.set(normalizedLine, (headerFooterCounts.get(normalizedLine) ?? 0) + 1);
  }

  const repeatedHeaderFooter = new Set(
    [...headerFooterCounts.entries()]
      .filter(([line, count]) => count > 1 && line.length < 90)
      .map(([line]) => line)
  );

  const keptLines = [];
  for (const rawLine of rawLines) {
    const normalizedLine = normalizeWhitespace(rawLine);
    if (!normalizedLine) continue;

    const lowered = normalizedLine.toLowerCase();
    const structured = isLikelyStructured(normalizedLine);
    if (repeatedHeaderFooter.has(lowered) && !structured) {
      continue;
    }

    const stripped = stripBoilerplate(normalizedLine);
    if (!stripped && !structured) {
      continue;
    }

    keptLines.push(stripped || normalizedLine);
  }

  const compact = keptLines.join('\n').replace(/\n{3,}/g, '\n\n').trim();
  const excerpt = keptLines.slice(0, 12).join('\n');

  return {
    text: compact,
    excerpt,
    stats: {
      originalLineCount: rawLines.length,
      keptLineCount: keptLines.length,
      removedLineCount: Math.max(rawLines.length - keptLines.length, 0)
    }
  };
}

function inferSupplier(text) {
  const supplierLine = text
    .split('\n')
    .find((line) => /^supplier\s*[:\-]/i.test(line) || /^from\s*[:\-]/i.test(line));

  if (supplierLine) {
    return supplierLine.split(/[:\-]/).slice(1).join(':').trim();
  }

  const companyLike = text
    .split('\n')
    .find((line) => /\b(inc\.?|llc|ltd\.?|corp\.?|gmbh|co\.)\b/i.test(line));

  return companyLike?.trim() || '';
}

function inferTotal(text) {
  const totalMatch = text.match(/\b(total|amount due|grand total)\b\s*[:\-]?\s*([$€£]?\s?[0-9][0-9,]*(?:\.[0-9]{2})?)/i);
  return totalMatch?.[2]?.replace(/\s+/g, '') || '';
}

function inferReferenceId(text) {
  const refMatch = text.match(/\b(po|invoice|quote|ref(?:erence)?)\b\s*[:#-]?\s*([A-Z0-9-]{3,})/i);
  return refMatch?.[2] || '';
}

function inferItems(text) {
  const lines = text.split('\n');
  const itemLines = lines.filter((line) => {
    const amount = /([$€£]?\s?[0-9][0-9,]*(?:\.[0-9]{2})?)/.test(line);
    const qty = /\bqty\b|\bquantity\b|\bx\d+\b|\b\d+\s+units?\b/i.test(line);
    return (TABLE_HINT.test(line) || qty) && amount;
  });

  return itemLines.slice(0, 20).map((line, index) => ({
    line: index + 1,
    description: line.trim()
  }));
}

export function parseDocument(sourceText) {
  const preprocessed = preprocessSourceText(sourceText);
  const text = preprocessed.text;

  const result = {
    supplier: inferSupplier(text),
    total: inferTotal(text),
    referenceId: inferReferenceId(text),
    items: inferItems(text),
    sourceExcerpt: preprocessed.excerpt,
    preprocessing: preprocessed.stats
  };

  const warnings = [];

  if (!result.supplier) {
    warnings.push({
      code: 'MISSING_SUPPLIER',
      field: 'supplier',
      severity: 'high',
      message: 'Supplier could not be confidently identified.'
    });
  }

  if (!result.total) {
    warnings.push({
      code: 'MISSING_TOTAL',
      field: 'total',
      severity: 'high',
      message: 'Total amount is missing or ambiguous.'
    });
  }

  if (!result.items.length) {
    warnings.push({
      code: 'EMPTY_ITEMS',
      field: 'items',
      severity: 'medium',
      message: 'No itemized lines were extracted from the document.'
    });
  }

  return {
    ...result,
    warnings,
    valid: warnings.length === 0
  };
}
