import { parseItems } from './parsing/index.mjs';

const BOILERPLATE_PATTERNS = [
  /all rights reserved/gi,
  /this (document|communication) (is|may be) confidential/gi,
  /please consider the environment before printing/gi,
  /terms and conditions apply/gi,
  /this message and any attachments?/gi,
  /generated by .* system/gi
];

const TABLE_HINT = /\|\s|\s\|\s|\t|\b(qty|quantity|unit price|amount|line total|sku|item)\b/i;
const REFERENCE_HINT = /(po|invoice|quote|ref|reference|id|order)\s*[:#-]?\s*[A-Z0-9][A-Z0-9-]{2,}/i;

function normalizeWhitespace(line) {
  return line.replace(/\u00A0/g, ' ').replace(/[ \t]+/g, ' ').trim();
}

function isLikelyStructured(line) {
  return TABLE_HINT.test(line) || REFERENCE_HINT.test(line);
}

function stripBoilerplate(line) {
  let next = line;
  for (const pattern of BOILERPLATE_PATTERNS) {
    next = next.replace(pattern, '').trim();
  }
  return next;
}

export function preprocessSourceText(text) {
  const normalizedText = String(text ?? '').replace(/\r\n?/g, '\n');
  const rawLines = normalizedText.split('\n').map((line) => line.trimEnd());
  const headerFooterCounts = new Map();

  for (const rawLine of rawLines) {
    const normalizedLine = normalizeWhitespace(rawLine).toLowerCase();
    if (normalizedLine.length < 3) continue;
    headerFooterCounts.set(normalizedLine, (headerFooterCounts.get(normalizedLine) ?? 0) + 1);
  }

  const repeatedHeaderFooter = new Set(
    [...headerFooterCounts.entries()]
      .filter(([line, count]) => count > 1 && line.length < 90)
      .map(([line]) => line)
  );

  const keptLines = [];
  for (const rawLine of rawLines) {
    const normalizedLine = normalizeWhitespace(rawLine);
    if (!normalizedLine) continue;

    const lowered = normalizedLine.toLowerCase();
    const structured = isLikelyStructured(normalizedLine);
    if (repeatedHeaderFooter.has(lowered) && !structured) {
      continue;
    }

    const stripped = stripBoilerplate(normalizedLine);
    if (!stripped && !structured) {
      continue;
    }

    keptLines.push(stripped || normalizedLine);
  }

  const compact = keptLines.join('\n').replace(/\n{3,}/g, '\n\n').trim();
  const excerpt = keptLines.slice(0, 12).join('\n');

  return {
    text: compact,
    excerpt,
    stats: {
      originalLineCount: rawLines.length,
      keptLineCount: keptLines.length,
      removedLineCount: Math.max(rawLines.length - keptLines.length, 0)
    }
  };
}

function inferSupplier(text) {
  const supplierLine = text
    .split('\n')
    .find((line) => /^supplier\s*[:\-]/i.test(line) || /^from\s*[:\-]/i.test(line));

  if (supplierLine) {
    return supplierLine.split(/[:\-]/).slice(1).join(':').trim();
  }

  const companyNamePattern = /\b([A-Z][\w'.-]*(?:\s+(?:&|and))?(?:\s+[A-Z][\w'.-]*){0,6}\s+(?:Limited|Ltd\.?|LLC|Inc\.?|Corp\.?|GmbH|Co\.?))\b/g;
  const companyLikeLine = text
    .split('\n')
    .find((line) => /\b(inc\.?|llc|ltd\.?|limited|corp\.?|gmbh|co\.)\b/i.test(line));

  if (companyLikeLine) {
    const matches = [...companyLikeLine.matchAll(companyNamePattern)];
    if (matches.length) {
      return matches[0][1].trim();
    }
  }

  const fullTextMatches = [...text.matchAll(companyNamePattern)];
  if (fullTextMatches.length) {
    return fullTextMatches[0][1].trim();
  }

  return '';
}

function inferTotal(text) {
  const amountPattern = '([$€£]\\s?[0-9][0-9,]*(?:\\.[0-9]{2})?|[0-9][0-9,]*\\.[0-9]{2})';
  const totalMatch = text.match(new RegExp(`\\b(total|amount due|grand total)\\b\\s*[:\\-]?\\s*${amountPattern}`, 'i'));
  if (totalMatch?.[2]) {
    return totalMatch[2].replace(/\s+/g, '');
  }

  const subtotalLikeMatch = text.match(new RegExp(`\\b(subtotal|net|total ex vat|ex vat|quotation(?:\\s+is)?(?:\\s+for)?)\\b[^\\n£$€]{0,40}${amountPattern}`, 'i'));
  if (subtotalLikeMatch?.[2]) {
    return subtotalLikeMatch[2].replace(/\s+/g, '');
  }

  const currencyAmounts = [...text.matchAll(/[$€£]\s?[0-9][0-9,]*(?:\.[0-9]{2})?/g)]
    .map((match) => match[0].replace(/\s+/g, ''));

  if (currencyAmounts.length) {
    return currencyAmounts[currencyAmounts.length - 1];
  }

  return '';
}

function inferReferenceId(text) {
  const refMatch = text.match(/\b(po|invoice|quote|ref(?:erence)?)\b\s*[:#-]?\s*([A-Z0-9-]{3,})/i);
  return refMatch?.[2] || '';
}

function inferItems(text, parsedItems) {
  const parsed = parsedItems ?? parseItems(text);
  if (parsed.rows.length) {
    return parsed.rows.map((row, index) => ({
      line: index + 1,
      description: row.description,
      qty: row.qty,
      unit: row.unit,
      lineTotal: row.line,
      source: row.source,
    }));
  }

  const sourceSegments = text.includes('\n')
    ? text.split('\n')
    : text.split(/(?<=\.)\s+(?=[A-Z])|\s+[•·-]\s+|(?=\b(?:Item Description|Subtotal|Total|VAT)\b)/i);

  const candidateLines = sourceSegments
    .flatMap((line) => {
      const normalized = normalizeWhitespace(line);
      if (normalized.length <= 180) return [normalized];
      return normalized
        .split(/(?<=\.)\s+(?=[A-Z])|(?=\b\d+(?:\.\d+)?\s*(?:x|each|ea|units?)\b)|(?=\b(?:Item Description|Cost|Subtotal|Total|VAT)\b)/i)
        .map(normalizeWhitespace);
    })
    .filter(Boolean);

  const itemLines = candidateLines.filter((line) => {
    const amount = /([$€£]?\s?[0-9][0-9,]*(?:\.[0-9]{2})?)/.test(line);
    const qty = /\bqty\b|\bquantity\b|\b\d+(?:\.\d+)?\s*(?:x|each|ea|units?)\b|\bx\s*\d+\b/i.test(line);
    const likelyNoise = /\b(terms|conditions|registered office|vat at the current rate|company no\.?|dear\s+sirs)\b/i.test(line);
    const containsUrl = /\b(?:https?:\/\/|www\.)\S+/i.test(line);
    const hasTablePipe = /\|/.test(line);
    return (TABLE_HINT.test(line) || qty) && amount && line.length <= 180 && !likelyNoise && !containsUrl && !hasTablePipe;
  });

  if (!itemLines.length) {
    const descriptionFallback = text.match(
      /item\s+description\s*[:\-]?\s*(.{12,180}?)(?=\s(?:vat\b|total\b|subtotal\b|[$€£]\s?\d|\d{2,}\.\d{2}|$))/i,
    );

    if (descriptionFallback?.[1]) {
      const cleanedDescription = normalizeWhitespace(
        descriptionFallback[1].replace(/^item\s+description\s*(?:cost)?\s*/i, ''),
      );

      return [
        {
          line: 1,
          description: cleanedDescription,
        },
      ];
    }
  }

  return [...new Set(itemLines.map((line) => normalizeWhitespace(line)))]
    .slice(0, 20)
    .map((line, index) => ({
      line: index + 1,
      description: line.replace(/^item\s+description\s*(?:cost)?\s*/i, '').trim(),
      qty: null,
      unit: null,
      lineTotal: null,
      source: 'legacy',
    }));
}

export function parseDocument(sourceText) {
  const preprocessed = preprocessSourceText(sourceText);
  const text = preprocessed.text;
  const parsedItems = parseItems(text);

  const result = {
    supplier: inferSupplier(text),
    total: inferTotal(text),
    referenceId: inferReferenceId(text),
    items: inferItems(text, parsedItems),
    sourceExcerpt: preprocessed.excerpt,
    preprocessing: preprocessed.stats
  };

  if (!result.total && parsedItems.detectedSubtotal !== null) {
    result.total = String(parsedItems.detectedSubtotal.toFixed(2));
  }

  const warnings = [];

  if (!result.supplier) {
    warnings.push({
      code: 'MISSING_SUPPLIER',
      field: 'supplier',
      severity: 'high',
      message: 'Supplier could not be confidently identified.'
    });
  }

  if (!result.total) {
    warnings.push({
      code: 'MISSING_TOTAL',
      field: 'total',
      severity: 'high',
      message: 'Total amount is missing or ambiguous.'
    });
  }

  if (!result.items.length) {
    warnings.push({
      code: 'EMPTY_ITEMS',
      field: 'items',
      severity: 'medium',
      message: 'No itemized lines were extracted from the document.'
    });
  }

  return {
    ...result,
    warnings,
    valid: warnings.length === 0
  };
}
